const String loginTitle = "Login To Your Account",
    signupTitle = "Create Your Account",
    forgotPasswordTitle = "Forgot Password",
    otpVerificationTitle = "Verify Your Account",
    emailPlaceHolder = "Email",
    firstnamePlaceHolder = "First Name",
    lastnamePlaceHolder = "Last Name",
    phoneNumberPlaceHolder = "Phone Number",
    passwordPlaceHolder = "Password",
    oldpasswordPlaceHolder = "Old password",
    newPasswordPlaceHolder = "New password",
    confirmNewPasswordPlaceHolder = "Confirm new password",
    confirmPasswordPlaceHolder = "Confirm password",
    forgotPassword = "Forgot Password?",
    dontHaveAccount = "Don't have an account?",
    signIn = "Sign in",
    signUp = "Sign up",
    confrim = "Confirm",
    operatorPlaceholder = "Operator",
    imeiPlaceholder = "Code IMEI";
const Map<String, String> errors = {
  "USER_NOT_FOUND": "User not found",
  "WRONG_CREDENTIALS": "Wrong credentials",
  'USER_ALREADY_EXISTS': 'User already exists',
  'OUT_OF_BUSINESS_WORKING_HOURS': "Out of business working hours",
  'OUT_OF_WORKING_HOURS_OF_ONE_OR_MORE_EMPLOYEES':
      "Out of working hours of 1 or more employees",
  'INVALID_SERVICE_OFFER_ASSIGNMENTS': "Invaild service offer assignment",
  'INVALID_USER': "Invalid user",
  'BUSINESS_NOT_FOUND': "Business not found",
  'EMPLOYEE_NOT_FOUND': "Employee not found",
  'BUSINESS_ALREADY_EXISTS': "Business already exists",
  'SERVICE_BOOKING_NOT_FOUND': "Service booking not found",
  'SERVICE_BOOKING_NOT_CONFIRMED': "Service booking not confirmed",
  'INVALID_CODE': "Invalid code",
  'EXPIRED_CODE': "Exipred code",
  'EVENT_NOT_FOUND': "Event not found",
  'SERVICE_OFFER_NOT_FOUND': "Service offer not found",
  'SERVICE_CAPTION_NOT_FOUND': "Service caption not found",
  'SERVICE_DESCRIPTION_NOT_FOUND': "Service description not found",
  'MEMBERSHIP_NOT_FOUND': "Membership not found",
  'UNAUTHORIZED': "Unauthorized",
  'BAD_REQUEST': "Bad request",
};
